version: '3.8'

services:
  emp-sys:
    image: "ds/employee-management-system"
    build:
      context: .
      dockerfile: "dockerfiles/api.dockerfile"
      target: "app-dev"
    command: "bash run_dev.sh"
    ports:
      - "8080:8080"
    volumes:
      - "./:/app/"
    env_file: ".env"
    depends_on:
      - "postgres"
    environment:
      - "ENV_FILE=.env"

  postgres:
    image: "postgres:11.5-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=emp_sys"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
