version: "3.9"
services:

  emp-sys:
    image: "ds/employee-system"
    build:
      context: .
      dockerfile: "dockerfiles/api.dockerfile"
      target: "app-dev"
    command: ["bash", "run_dev.sh"]
    ports:
      - "8080:8080"
    volumes:
      - "./:/app/"
    env_file: ".env"
    depends_on:
      - "postgres"

      - "minio"
    environment:
      - "ENV_FILE=.env"

  minio:
    image: "minio/minio:RELEASE.2019-07-05T21-20-21Z"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "minio_dev_access_key"
      MINIO_SECRET_KEY: "minio_dev_secret_key"
    entrypoint: sh
    command: >
      -c "mkdir -p /data/profile-storage-ems-com
      && /usr/bin/docker-entrypoint.sh server /data"
    logging:
      driver: "none"

    environment:
      - "ENV_FILE=.env"

  postgres:
    image: "library/postgres:13.4-alpine"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=ems"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
